-- Drop tables in reverse dependency order to avoid foreign key constraint errors

DROP TABLE IF EXISTS LEARNING_PLATFORM.SECTIONS;

DROP TABLE IF EXISTS LEARNING_PLATFORM.LECTURES;

DROP TABLE IF EXISTS LEARNING_PLATFORM.COURSES;

DROP TABLE IF EXISTS LEARNING_PLATFORM.USERS;

-- Drop the schema
DROP SCHEMA IF EXISTS LEARNING_PLATFORM;
