-- Rollback for: ALTER TABLE LECTURES ADD COLUMN LECTURE_ORDER INT NOT NULL;
ALTER TABLE LEARNING_PLATFORM.LECTURES DROP COLUMN LECTURE_ORDER;

-- Rollback for: ALTER TABLE SECTIONS ADD COLUMN SECTION_ORDER INT NOT NULL;
ALTER TABLE LEARNING_PLATFORM.SECTIONS DROP COLUMN SECTION_ORDER;
