CREATE TABLE IF NOT EXISTS LEARNING_PLATFORM.SCHEMA_ROLLBACK_LOG (
  ID SERIAL PRIMARY KEY,
  BATCH_ID INT NOT NULL,
  MIGRATION_VERSION VARCHAR NOT NULL,
  APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
